name: flutter_shop
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

  # for state management
  get: ^4.6.6

  # for svg icons
  flutter_svg: ^2.0.9

  # shimmer effect
  shimmer: ^3.0.0

  # cached network image
  cached_network_image: ^3.3.0

  # networking library
  http: ^1.1.0

  intl: ^0.19.0

   # Hive noSQL DB
  hive: ^2.2.3
  path_provider: ^2.1.1
  hive_flutter: ^1.1.0

  # support animation
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/
    - assets/fonts/
    - assets/animations/
